// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qofnibjdpldqwwaepjtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZm5pYmpkcGxkcXd3YWVwanRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODA2ODYsImV4cCI6MjA2MjE1NjY4Nn0.-DZC6fePsGVMn2bGG8xmFIydkg0mMpsitf0WwlsBaFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);